/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author jgale
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public GUI() {

        initComponents();
        
        this.chronoResetBtn.setEnabled(false);
        this.chronoSaveBtn.setEnabled(false);
        this.chronoStopBtn.setEnabled(false);
        this.timerStartBtn.setEnabled(false);
        this.timerStopBtn.setEnabled(false);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chronoClock = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        chronoStartBtn = new javax.swing.JButton();
        chronoStopBtn = new javax.swing.JButton();
        chronoSaveBtn = new javax.swing.JButton();
        chronoResetBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        timerClock = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        timerSetBtn = new javax.swing.JButton();
        timerStartBtn = new javax.swing.JButton();
        timerStopBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Chrono");

        chronoClock.setBackground(new java.awt.Color(0, 51, 102));
        chronoClock.setFont(new java.awt.Font("Seven Segment", 0, 36)); // NOI18N
        chronoClock.setForeground(new java.awt.Color(255, 153, 0));
        chronoClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chronoClock.setText("00:00:00");
        chronoClock.setOpaque(true);

        chronoStartBtn.setText("Start");
        jPanel3.add(chronoStartBtn);

        chronoStopBtn.setText("Stop");
        jPanel3.add(chronoStopBtn);

        chronoSaveBtn.setText("Save");
        jPanel3.add(chronoSaveBtn);

        chronoResetBtn.setText("Reset");
        jPanel3.add(chronoResetBtn);

        jPanel4.setLayout(new java.awt.GridLayout(5, 2));

        jLabel5.setText("1.");
        jPanel4.add(jLabel5);

        jLabel6.setText("6.");
        jPanel4.add(jLabel6);

        jLabel7.setText("2.");
        jPanel4.add(jLabel7);

        jLabel8.setText("7.");
        jPanel4.add(jLabel8);

        jLabel9.setText("3.");
        jPanel4.add(jLabel9);

        jLabel10.setText("8.");
        jPanel4.add(jLabel10);

        jLabel11.setText("4.");
        jPanel4.add(jLabel11);

        jLabel12.setText("9.");
        jPanel4.add(jLabel12);

        jLabel13.setText("5.");
        jPanel4.add(jLabel13);

        jLabel14.setText("10.");
        jPanel4.add(jLabel14);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chronoClock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chronoClock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Timer");

        timerClock.setBackground(new java.awt.Color(0, 51, 102));
        timerClock.setFont(new java.awt.Font("Seven Segment", 0, 36)); // NOI18N
        timerClock.setForeground(new java.awt.Color(255, 153, 0));
        timerClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerClock.setText("00:00:00");
        timerClock.setOpaque(true);

        timerSetBtn.setText("Set Time");
        jPanel5.add(timerSetBtn);

        timerStartBtn.setText("Start");
        jPanel5.add(timerStartBtn);

        timerStopBtn.setText("Stop");
        jPanel5.add(timerStopBtn);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(timerClock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timerClock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel chronoClock;
    public javax.swing.JButton chronoResetBtn;
    public javax.swing.JButton chronoSaveBtn;
    public javax.swing.JButton chronoStartBtn;
    public javax.swing.JButton chronoStopBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JLabel timerClock;
    public javax.swing.JButton timerSetBtn;
    public javax.swing.JButton timerStartBtn;
    public javax.swing.JButton timerStopBtn;
    // End of variables declaration//GEN-END:variables
}
